version: '3.6'

services:
  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb
    env_file:
      - .env
    restart: always
    volumes:
      - db:/var/lib/mysql
    networks:
      - inception
  
  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress
    env_file:
      - .env
    volumes:
      - wp:/var/www/html/wordpress
    depends_on:
      - mariadb
    restart: always
    networks:
      - inception

  nginx:
    container_name: nginx
    build: ./requirements/nginx
    hostname: localhost
    volumes:
      - wp:/var/www/html/wordpress
    ports:
      - 443:443
    restart: always
    depends_on:
      - wordpress
    networks:
      - inception
  
  redis:
    container_name: redis
    build: ./requirements/bonus/redis
    ports:
      - 6379:6379
    restart: always
    networks:
      - inception

  site:
    container_name: site
    build: ./requirements/bonus/mysite
    ports:
      - 8080:8080
    restart: always
    networks:
      - inception

  prometheus:
    container_name: prometheus
    build: ./requirements/bonus/prometheus
    ports:
      - 9090:9090
    restart: always
    networks:
      - inception

  ftp:
    container_name: ftp
    build: ./requirements/bonus/ftp
    env_file:
      - .env
    ports:
      - "21:21"
      - "21000:21000"
    volumes:
      - wp:/home/nfarfetc/ftp/files
    restart: always
    networks:
      - inception
  
  adminer:
    container_name: adminer
    build: ./requirements/bonus/adminer
    ports:
      - 7077:7077
    depends_on:
      - nginx
    networks:
      - inception
    restart: always
  
networks:
  inception:
    driver: bridge

volumes:
  db:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/${USER}/data/db
  wp:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/${USER}/data/wp