global:
  scrape_interval:     5s
  evaluation_interval: 5s
  external_labels:
      monitor: 'codelab-monitor'

rule_files:
  - "targets.rules"
  - "host.rules"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
  
  - job_name: 'site'
    static_configs:
      - targets: ['localhost:8080']