CREATE DATABASE wordpress;
CREATE USER 'nfarfetc'@'%' IDENTIFIED BY '1111';
GRANT ALL PRIVILEGES ON wordpress.* TO 'nfarfetc'@'%';
FLUSH PRIVILEGES;
ALTER USER 'root'@'localhost' IDENTIFIED BY '1111';